environment:
  matrix:
    - nodejs_version: "12"
      TARGET: test
    - nodejs_version: "12"
      TARGET: test-multi
    - nodejs_version: "10"
      TARGET: test
    - nodejs_version: "10"
      TARGET: test-multi

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version
  - npm run %TARGET%

build: off
