environment:
  NODE_CONFIG: '{"db": {"host": "localhost"}}'
  PGUSER: postgres
  PGPASSWORD: Password12!
  POSTGRES_PATH: C:\Program Files\PostgreSQL\10
  matrix:
    - nodejs_version: "12.2.0"
      TARGET: test
    - nodejs_version: "12.2.0"
      TARGET: test-multi
    - nodejs_version: "10.15.3"
      TARGET: test
    - nodejs_version: "10.15.3"
      TARGET: test-multi

services:
  - postgresql101

install:
#  - ps: Update-NodeJsInstallation $env:nodejs_version x64
  - ps: Remove-NodeJsInstallation $(Get-InstalledNodeJsVersion).version $(Get-InstalledNodeJsVersion).bitness
  - ps: cmd /c start /wait msiexec /i $(Get-NodeJsInstallPackage $env:nodejs_version x64) /q
  - npm install

test_script:
  - set path=%postgres_path%\\bin;%path%
  - psql -c "create database 'qlobber-pg';"
  - node --version
  - npm --version
  - npm run %TARGET%

build: off
