environment:
  matrix:
    - nodejs_version: "12"
      TARGET: test
    - nodejs_version: "12"
      TARGET: test-multi
    - nodejs_version: "10"
      TARGET: test
    - nodejs_version: "10"
      TARGET: test-multi

install:
#  - ps: Update-NodeJsInstallation $env:nodejs_version x64
  - ps: Remove-NodeJsInstallation $(Get-InstalledNodeJsVersion).version $(Get-InstalledNodeJsVersion).bitness
  - ps: cmd /c start /wait msiexec /i $(Get-NodeJsInstallPackage $env:nodejs_version x64) /q
  - npm install

test_script:
  - node --version
  - npm --version
  - npm run %TARGET%

build: off
